# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc1.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(478, 675)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 80, 441, 551))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_n5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pushButton_n5.sizePolicy().hasHeightForWidth())
        self.pushButton_n5.setSizePolicy(sizePolicy)
        self.pushButton_n5.setMinimumSize(QtCore.QSize(104, 103))
        self.pushButton_n5.setMaximumSize(QtCore.QSize(103, 103))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_n5.setFont(font)
        self.pushButton_n5.setObjectName("pushButton_n5")
        self.gridLayout.addWidget(self.pushButton_n5, 2, 1, 1, 1)
        self.pushButton_n1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pushButton_n1.sizePolicy().hasHeightForWidth())
        self.pushButton_n1.setSizePolicy(sizePolicy)
        self.pushButton_n1.setMinimumSize(QtCore.QSize(103, 103))
        self.pushButton_n1.setMaximumSize(QtCore.QSize(103, 103))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_n1.setFont(font)
        self.pushButton_n1.setObjectName("pushButton_n1")
        self.gridLayout.addWidget(self.pushButton_n1, 3, 0, 1, 1)
        self.pushButton_n0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pushButton_n0.sizePolicy().hasHeightForWidth())
        self.pushButton_n0.setSizePolicy(sizePolicy)
        self.pushButton_n0.setMinimumSize(QtCore.QSize(103, 103))
        self.pushButton_n0.setMaximumSize(QtCore.QSize(103, 103))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_n0.setFont(font)
        self.pushButton_n0.setCheckable(False)
        self.pushButton_n0.setObjectName("pushButton_n0")
        self.gridLayout.addWidget(self.pushButton_n0, 4, 0, 1, 1)
        self.pushButton_equal = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pushButton_equal.sizePolicy().hasHeightForWidth())
        self.pushButton_equal.setSizePolicy(sizePolicy)
        self.pushButton_equal.setMinimumSize(QtCore.QSize(103, 103))
        self.pushButton_equal.setMaximumSize(QtCore.QSize(103, 103))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_equal.setFont(font)
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.gridLayout.addWidget(self.pushButton_equal, 4, 2, 1, 1)
        self.pushButton_mul = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pushButton_mul.sizePolicy().hasHeightForWidth())
        self.pushButton_mul.setSizePolicy(sizePolicy)
        self.pushButton_mul.setMinimumSize(QtCore.QSize(103, 103))
        self.pushButton_mul.setMaximumSize(QtCore.QSize(103, 103))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_mul.setFont(font)
        self.pushButton_mul.setObjectName("pushButton_mul")
        self.gridLayout.addWidget(self.pushButton_mul, 3, 3, 1, 1)
        self.pushButton_n9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pushButton_n9.sizePolicy().hasHeightForWidth())
        self.pushButton_n9.setSizePolicy(sizePolicy)
        self.pushButton_n9.setMinimumSize(QtCore.QSize(103, 103))
        self.pushButton_n9.setMaximumSize(QtCore.QSize(103, 103))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_n9.setFont(font)
        self.pushButton_n9.setObjectName("pushButton_n9")
        self.gridLayout.addWidget(self.pushButton_n9, 1, 2, 1, 1)
        self.pushButton_n6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pushButton_n6.sizePolicy().hasHeightForWidth())
        self.pushButton_n6.setSizePolicy(sizePolicy)
        self.pushButton_n6.setMinimumSize(QtCore.QSize(103, 103))
        self.pushButton_n6.setMaximumSize(QtCore.QSize(103, 103))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_n6.setFont(font)
        self.pushButton_n6.setObjectName("pushButton_n6")
        self.gridLayout.addWidget(self.pushButton_n6, 2, 2, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clear.sizePolicy().hasHeightForWidth())
        self.pushButton_clear.setSizePolicy(sizePolicy)
        self.pushButton_clear.setMinimumSize(QtCore.QSize(103, 103))
        self.pushButton_clear.setMaximumSize(QtCore.QSize(103, 103))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout.addWidget(self.pushButton_clear, 0, 0, 1, 1)
        self.pushButton_n3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pushButton_n3.sizePolicy().hasHeightForWidth())
        self.pushButton_n3.setSizePolicy(sizePolicy)
        self.pushButton_n3.setMinimumSize(QtCore.QSize(103, 103))
        self.pushButton_n3.setMaximumSize(QtCore.QSize(103, 103))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_n3.setFont(font)
        self.pushButton_n3.setObjectName("pushButton_n3")
        self.gridLayout.addWidget(self.pushButton_n3, 3, 2, 1, 1)
        self.pushButton_n2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pushButton_n2.sizePolicy().hasHeightForWidth())
        self.pushButton_n2.setSizePolicy(sizePolicy)
        self.pushButton_n2.setMinimumSize(QtCore.QSize(104, 103))
        self.pushButton_n2.setMaximumSize(QtCore.QSize(103, 103))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_n2.setFont(font)
        self.pushButton_n2.setObjectName("pushButton_n2")
        self.gridLayout.addWidget(self.pushButton_n2, 3, 1, 1, 1)
        self.pushButton_n8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pushButton_n8.sizePolicy().hasHeightForWidth())
        self.pushButton_n8.setSizePolicy(sizePolicy)
        self.pushButton_n8.setMinimumSize(QtCore.QSize(104, 103))
        self.pushButton_n8.setMaximumSize(QtCore.QSize(103, 103))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_n8.setFont(font)
        self.pushButton_n8.setObjectName("pushButton_n8")
        self.gridLayout.addWidget(self.pushButton_n8, 1, 1, 1, 1)
        self.pushButton_div = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pushButton_div.sizePolicy().hasHeightForWidth())
        self.pushButton_div.setSizePolicy(sizePolicy)
        self.pushButton_div.setMinimumSize(QtCore.QSize(103, 103))
        self.pushButton_div.setMaximumSize(QtCore.QSize(103, 103))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_div.setFont(font)
        self.pushButton_div.setObjectName("pushButton_div")
        self.gridLayout.addWidget(self.pushButton_div, 4, 3, 1, 1)
        self.pushButton_n7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pushButton_n7.sizePolicy().hasHeightForWidth())
        self.pushButton_n7.setSizePolicy(sizePolicy)
        self.pushButton_n7.setMinimumSize(QtCore.QSize(103, 103))
        self.pushButton_n7.setMaximumSize(QtCore.QSize(103, 103))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_n7.setFont(font)
        self.pushButton_n7.setObjectName("pushButton_n7")
        self.gridLayout.addWidget(self.pushButton_n7, 1, 0, 1, 1)
        self.pushButton_coma = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pushButton_coma.sizePolicy().hasHeightForWidth())
        self.pushButton_coma.setSizePolicy(sizePolicy)
        self.pushButton_coma.setMinimumSize(QtCore.QSize(104, 103))
        self.pushButton_coma.setMaximumSize(QtCore.QSize(103, 103))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_coma.setFont(font)
        self.pushButton_coma.setObjectName("pushButton_coma")
        self.gridLayout.addWidget(self.pushButton_coma, 4, 1, 1, 1)
        self.pushButton_add = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pushButton_add.sizePolicy().hasHeightForWidth())
        self.pushButton_add.setSizePolicy(sizePolicy)
        self.pushButton_add.setMinimumSize(QtCore.QSize(103, 103))
        self.pushButton_add.setMaximumSize(QtCore.QSize(103, 103))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout.addWidget(self.pushButton_add, 1, 3, 1, 1)
        self.pushButton_n4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pushButton_n4.sizePolicy().hasHeightForWidth())
        self.pushButton_n4.setSizePolicy(sizePolicy)
        self.pushButton_n4.setMinimumSize(QtCore.QSize(103, 103))
        self.pushButton_n4.setMaximumSize(QtCore.QSize(103, 103))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_n4.setFont(font)
        self.pushButton_n4.setObjectName("pushButton_n4")
        self.gridLayout.addWidget(self.pushButton_n4, 2, 0, 1, 1)
        self.pushButton_sub = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pushButton_sub.sizePolicy().hasHeightForWidth())
        self.pushButton_sub.setSizePolicy(sizePolicy)
        self.pushButton_sub.setMinimumSize(QtCore.QSize(103, 103))
        self.pushButton_sub.setMaximumSize(QtCore.QSize(103, 103))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_sub.setFont(font)
        self.pushButton_sub.setObjectName("pushButton_sub")
        self.gridLayout.addWidget(self.pushButton_sub, 2, 3, 1, 1)
        self.pushButton_back = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_back.setMinimumSize(QtCore.QSize(0, 103))
        self.pushButton_back.setMaximumSize(QtCore.QSize(103, 103))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.gridLayout.addWidget(self.pushButton_back, 0, 2, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(20, 10, 441, 71))
        self.lcdNumber.setObjectName("lcdNumber")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 478, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_n5.setText(_translate("MainWindow", "5"))
        self.pushButton_n1.setText(_translate("MainWindow", "1"))
        self.pushButton_n0.setText(_translate("MainWindow", "0"))
        self.pushButton_equal.setText(_translate("MainWindow", "="))
        self.pushButton_mul.setText(_translate("MainWindow", "*"))
        self.pushButton_n9.setText(_translate("MainWindow", "9"))
        self.pushButton_n6.setText(_translate("MainWindow", "6"))
        self.pushButton_clear.setText(_translate("MainWindow", "C"))
        self.pushButton_n3.setText(_translate("MainWindow", "3"))
        self.pushButton_n2.setText(_translate("MainWindow", "2"))
        self.pushButton_n8.setText(_translate("MainWindow", "8"))
        self.pushButton_div.setText(_translate("MainWindow", "/"))
        self.pushButton_n7.setText(_translate("MainWindow", "7"))
        self.pushButton_coma.setText(_translate("MainWindow", ","))
        self.pushButton_add.setText(_translate("MainWindow", "+"))
        self.pushButton_n4.setText(_translate("MainWindow", "4"))
        self.pushButton_sub.setText(_translate("MainWindow", "-"))
        self.pushButton_back.setText(_translate("MainWindow", "Back <-"))
